### ISSUE TITLE
Video Tutorial in Windows

### ISSUE THREAD

**Issue by legendz97** [mickleroy/aem-pokego-lure-client#26]
Can you make one please? On how to use this

**Comment by mickleroy** [comment]
Thanks for reaching out. 

This project is still under active development but we are planning on making a screencast to demonstrate it's use within the next couple of weeks. 

I'll update this issue once it's made available.

**Comment by legendz97** [comment]
Thank you

**Comment by mickleroy** [comment]
Hi @legendz97 

I've updated the README with a link to a screencast. I'd also like to emphasize that this application requires Adobe Experience Manager to run.

Hope it helps.
