### ISSUE TITLE
[MANAGE] Store Google Maps API key

### ISSUE THREAD

**Issue by nletts** [mickleroy/aem-pokego-lure-client#8]
Provide OSGI service to store Google Maps API key

**Comment by mickleroy** [comment]
The following service has been created: `aem.pokego.lure.services.impl.PokeGoLureConfigImpl` a.k.a "Pokemon Go Lure Configuration"

**Comment by mickleroy** [comment]
The key can be retrieved from JSPs using `${pokego:mapsApiKey(sling)}`
